Feature/avatar
hiromuota166/MoodHub pull request #23
Opened 2023-12-07 15:10 UTC by hiromuota166

2023-12-07 16:41 UTC, Shunkicreate commented on src/components/UserList.tsx
> +  }, []);
NITS 粗探しになっちゃうけど、このuseEffectの中の挙動を解説出来たら完璧やと思います。

2023-12-07 16:44 UTC, Shunkicreate requested changes

2023-12-07 16:44 UTC, Shunkicreate commented on src/components/UserList.tsx
> +  // もしログインしてない場合、アバターは表示しない
imo React.useStateという表記ではなく、useStateという表記にして、import分を変更して{useEffect, useState} from reactみたいな形にしてほしい。この形式はあんま使わんな。

2023-12-07 16:44 UTC, Shunkicreate commented on src/app/providers 2.tsx
> +}
must 〇〇 2みたいなファイルがまた謎に追加されてるけど、全部消しといてー

2023-12-08 00:28 UTC, hiromuota166 commented on src/components/UserList.tsx
> +  }, []);
authの中のphotoURLが存在していればsetAvatarにその値を入れて完了。なかったら空のstringを入れてデフォルトのAvatarを表示。nullじゃなくて空の""を使っているのはchakraのAvatar内のsrcがstring | undefinedだったからだと勝手に思ってます。

2023-12-08 08:22 UTC, Shunkicreate commented on src/components/UserList.tsx
> +  }, []);
>nullじゃなくて空の""を使っているのはchakraのAvatar内のsrcがstring | undefinedだったから
これだと、url = undefinedとかでもいいかもね

2023-12-08 08:26 UTC, Shunkicreate requested changes

2023-12-08 08:26 UTC, Shunkicreate commented on src/functions/requestDeviceMotionPermission 2.ts
> +export default requestDeviceMotionPermission;
must まだなんとか2消えてないいいい
publicの中のファイルと、storiesの中のファイル！

2023-12-09 05:15 UTC, hiromuota166 commented on src/functions/requestDeviceMotionPermission 2.ts
> +export default requestDeviceMotionPermission;
あれえ笑

2023-12-09 07:58 UTC, Shunkicreate approved these changes
LGTM！

2023-12-09 07:58 UTC, merged