Feature/UI/modification
hiromuota166/MoodHub pull request #24
Opened 2023-12-07 16:10 UTC by hiromuota166

2023-12-07 16:56 UTC, Shunkicreate requested changes

2023-12-07 16:56 UTC, Shunkicreate commented on src/app/test/page.tsx
> +export default Page;
must テストページは消しといてほしいー！
あとここからは余談やけど、今はstorybookを整備したから、UIのテストはそっちでするようにしてもらいたいな。
全く同じことができるし、storybookの方ができることが多いんよ。

2023-12-07 16:56 UTC, Shunkicreate commented on src/components/Header.tsx
> +        </button>
imo これは普通のページ遷移やからaタグ使ってほしい！そうすると、handleclick関数は用意戦でいいし、onclickも要らんし、use clientも消せる！

2023-12-07 16:56 UTC, Shunkicreate commented on src/components/ModalWhole.tsx
>            height={500}
これ最高。天才

2023-12-07 16:56 UTC, Shunkicreate commented on src/components/ModalWhole.tsx
> +          className="flex w-10 mt-5 absolute right-0 top-0"
imo alt属性はそのアイコンが何を表しているかをちゃんと記述した方がいいから、この場合は検索ボタンのアイコンとか、検索ボタンとかそういったのを書く方がアクセシビリティ的にいいな

2023-12-08 00:40 UTC, hiromuota166 commented on src/app/test/page.tsx
> +export default Page;
わかりました！

2023-12-08 00:43 UTC, hiromuota166 commented on src/components/ModalWhole.tsx
> +          className="flex w-10 mt-5 absolute right-0 top-0"
"検索ボタン"にします。

2023-12-08 08:18 UTC, Shunkicreate approved these changes
LGTM!

2023-12-08 08:19 UTC, merged