Feature/modal UI/modification
hiromuota166/MoodHub pull request #25
Opened 2023-12-09 07:39 UTC by hiromuota166

2023-12-09 08:09 UTC, Shunkicreate requested changes

2023-12-09 08:09 UTC, Shunkicreate commented on src/components/ModalWhole.tsx
>        <Modal isOpen={modalIsOpen} style={ModalCss} ariaHideApp={false}>
must ここのボタンが画面的には横一杯に広がってて、アイコンの位置とボタンを押せる範囲が大きく違ってたから修正しといてほしい！

2023-12-09 08:11 UTC, Shunkicreate commented on src/components/ModalWhole.tsx
>          >
imo sticky使うのはgood

2023-12-10 13:21 UTC, hiromuota166 commented on src/components/ModalWhole.tsx
>        <Modal isOpen={modalIsOpen} style={ModalCss} ariaHideApp={false}>
たぶん違うpr出直してあるはず！feature/UI/Modificationみたいなやつです

2023-12-15 01:59 UTC, Shunkicreate commented on src/components/ModalWhole.tsx
>        <Modal isOpen={modalIsOpen} style={ModalCss} ariaHideApp={false}>
これまだ治ってないいいいいい

2023-12-30 08:25 UTC, Shunkicreate approved these changes
LGTM！！！

2023-12-30 08:25 UTC, merged