registerのエラー文確認済み
hiromuota166/MoodHub pull request #29
Opened 2024-01-29 02:57 UTC by hiromuota166

・ログインにregister追加
・カテゴリ選択からregister処理を取り除く

2024-01-29 08:52 UTC, MasamichiKanakubo commented on src/components/GoogleLoginBtn.tsx
>          console.log(user);
ここのデバッグは後で消しましょう

2024-01-29 08:52 UTC, MasamichiKanakubo commented on src/components/GoogleLoginBtn.tsx
> +          age: null, // 年齢が必要な場合は設定
ここはあってると思います。`categories`のところは必要に応じす必ず空のリストであって欲しい

2024-01-29 08:52 UTC, MasamichiKanakubo commented on src/components/GoogleLoginBtn.tsx
> +
僕レベルだと、このコードで何をしたいのかコメントがないとレビューできないです、ごめんなさい。このブロックのレビューはしゅんき君に丸投げします

2024-01-31 13:38 UTC, Shunkicreate requested changes

2024-01-31 13:38 UTC, Shunkicreate commented on src/components/GoogleLoginBtn.tsx
> +
```ts
import useApolloQuery from "@/lib/apollo/useApolloQuery";
const { registerUserFunc } = useApolloQuery();
```
これだけで動くよ

2024-02-03 04:17 UTC, Shunkicreate approved these changes
LGTMです！！！！！！

2024-02-03 04:17 UTC, merged