chakraを使ったloadingを早めにpr
hiromuota166/MoodHub pull request #7
Opened 2023-10-23 02:07 UTC by hiromuota166

2023-10-23 04:54 UTC, Shunkicreate requested changes

2023-10-23 04:54 UTC, Shunkicreate commented on src/components/IsLoading.tsx
> +}
imo これchakraUIからそのまま持ってきてるけど色がこのteal系の方がよくない？
https://chakra-ui.com/docs/styled-system/theme#teal

2023-10-23 05:04 UTC, hiromuota166 commented on src/components/IsLoading.tsx
> +}
確かに、他の色と合わせた方がいいですね
100くらいで行きます

2023-10-23 05:08 UTC, hiromuota166 commented on src/components/IsLoading.tsx
> +}
薄いんで400で。

2023-10-24 06:13 UTC, Shunkicreate submitted a review, later dismissed
LTGM!

2023-10-24 08:22 UTC, Shunkicreate approved these changes
LGTM！
マージしたコミットしたからブロックされたんかな

2023-10-24 08:22 UTC, merged